/**
 * SpamService — Spam Template Management & Delivery
 * @file scripts/services/SpamService.js
 * @module cyberpunkred-messenger
 * @description Manages built-in and custom spam templates, resolves variable
 *              tokens, delivers spam messages via MessageService, and handles
 *              auto-spam network triggers.
 */

import { MODULE_ID } from '../utils/constants.js';
import { log } from '../utils/helpers.js';
import {
  BUILTIN_SPAM_TEMPLATES,
  SPAM_CATEGORIES,
  RANDOM_CORPOS,
  RANDOM_DISTRICTS,
} from '../data/spam-templates.js';

/** @type {string} Settings key for custom templates */
const SETTING_CUSTOM_TEMPLATES = 'spamCustomTemplates';

/** @type {string} Settings key for auto-spam network config */
const SETTING_AUTO_SPAM = 'spamAutoConfig';

export class SpamService {

  // ═══════════════════════════════════════════════════════════
  //  Construction
  // ═══════════════════════════════════════════════════════════

  constructor() {
    /** @type {Array<object>} Cached custom templates (loaded from settings) */
    this._customTemplates = [];

    /** @type {object} Auto-spam config per network */
    this._autoConfig = {};

    /** @type {number} Session counter — spam sent this session */
    this._sentThisSession = 0;

    /** @type {number} Session counter — auto-generated this session */
    this._autoGeneratedThisSession = 0;
  }

  // ═══════════════════════════════════════════════════════════
  //  Initialization
  // ═══════════════════════════════════════════════════════════

  /**
   * Register module settings and load saved data.
   * Call once during init phase.
   */
  registerSettings() {
    game.settings.register(MODULE_ID, SETTING_CUSTOM_TEMPLATES, {
      name: 'Custom Spam Templates',
      scope: 'world',
      config: false,
      type: Array,
      default: [],
    });

    game.settings.register(MODULE_ID, SETTING_AUTO_SPAM, {
      name: 'Auto-Spam Network Configuration',
      scope: 'world',
      config: false,
      type: Object,
      default: {},
    });
  }

  /**
   * Load saved data from settings. Call during ready phase.
   */
  load() {
    try {
      this._customTemplates = game.settings.get(MODULE_ID, SETTING_CUSTOM_TEMPLATES) ?? [];
      this._autoConfig = game.settings.get(MODULE_ID, SETTING_AUTO_SPAM) ?? {};
      log.info(`SpamService loaded: ${this._customTemplates.length} custom templates, ${Object.keys(this._autoConfig).length} auto-spam configs`);
    } catch (err) {
      console.warn('NCM | SpamService: Failed to load settings', err);
      this._customTemplates = [];
      this._autoConfig = {};
    }
  }

  // ═══════════════════════════════════════════════════════════
  //  Template Queries
  // ═══════════════════════════════════════════════════════════

  /** @returns {object} Category definitions with icons and colors */
  get categories() {
    return SPAM_CATEGORIES;
  }

  /** @returns {number} Total template count (built-in + custom) */
  get totalCount() {
    return BUILTIN_SPAM_TEMPLATES.length + this._customTemplates.length;
  }

  /** @returns {number} Custom template count */
  get customCount() {
    return this._customTemplates.length;
  }

  /** @returns {number} Spam sent this session */
  get sentThisSession() {
    return this._sentThisSession;
  }

  /** @returns {number} Auto-generated spam this session */
  get autoGeneratedThisSession() {
    return this._autoGeneratedThisSession;
  }

  /**
   * Get all templates (built-in + custom), optionally filtered by category.
   * @param {string} [category] Filter by category key (e.g. 'corpo', 'scam')
   * @returns {Array<object>}
   */
  getTemplates(category = null) {
    const builtIn = BUILTIN_SPAM_TEMPLATES.map(t => ({ ...t, isCustom: false }));
    const custom = this._customTemplates.map(t => ({ ...t, isCustom: true }));
    let all = [...builtIn, ...custom];

    if (category && category !== 'all') {
      all = all.filter(t => t.category === category);
    }

    return all;
  }

  /**
   * Get a single template by ID.
   * @param {string} templateId
   * @returns {object|null}
   */
  getTemplate(templateId) {
    const builtIn = BUILTIN_SPAM_TEMPLATES.find(t => t.id === templateId);
    if (builtIn) return { ...builtIn, isCustom: false };

    const custom = this._customTemplates.find(t => t.id === templateId);
    if (custom) return { ...custom, isCustom: true };

    return null;
  }

  /**
   * Get template counts per category.
   * @returns {object} Map of category → count
   */
  getCategoryCounts() {
    const counts = { all: 0 };
    for (const key of Object.keys(SPAM_CATEGORIES)) {
      counts[key] = 0;
    }
    counts.custom = 0;

    for (const t of BUILTIN_SPAM_TEMPLATES) {
      counts[t.category] = (counts[t.category] || 0) + 1;
      counts.all++;
    }
    for (const t of this._customTemplates) {
      counts[t.category] = (counts[t.category] || 0) + 1;
      counts.custom++;
      counts.all++;
    }

    return counts;
  }

  // ═══════════════════════════════════════════════════════════
  //  Custom Template CRUD
  // ═══════════════════════════════════════════════════════════

  /**
   * Create a new custom spam template.
   * @param {object} data Template data
   * @param {string} data.fromName Sender display name
   * @param {string} data.fromEmail Sender email
   * @param {string} data.category Category key
   * @param {string} data.subject Subject line
   * @param {string} data.body Message body (supports tokens)
   * @param {string} [data.networkFilter] Optional network restriction
   * @returns {Promise<object>} The created template
   */
  async createTemplate(data) {
    const template = {
      id: `custom-${foundry.utils.randomID(8)}`,
      category: data.category || 'custom',
      fromName: data.fromName || 'Unknown Sender',
      fromEmail: data.fromEmail || 'unknown@spam.nc',
      subject: data.subject || '(no subject)',
      body: data.body || '',
      networkFilter: data.networkFilter || null,
      createdAt: new Date().toISOString(),
    };

    this._customTemplates.push(template);
    await this._saveCustomTemplates();
    log.info(`SpamService: Created custom template "${template.subject}" (${template.id})`);
    return template;
  }

  /**
   * Update an existing custom template.
   * @param {string} templateId
   * @param {object} updates Partial data to merge
   * @returns {Promise<object|null>}
   */
  async updateTemplate(templateId, updates) {
    const idx = this._customTemplates.findIndex(t => t.id === templateId);
    if (idx === -1) return null;

    const allowed = ['fromName', 'fromEmail', 'category', 'subject', 'body', 'networkFilter'];
    for (const key of allowed) {
      if (updates[key] !== undefined) {
        this._customTemplates[idx][key] = updates[key];
      }
    }

    await this._saveCustomTemplates();
    log.info(`SpamService: Updated custom template ${templateId}`);
    return this._customTemplates[idx];
  }

  /**
   * Delete a custom template.
   * @param {string} templateId
   * @returns {Promise<boolean>}
   */
  async deleteTemplate(templateId) {
    const idx = this._customTemplates.findIndex(t => t.id === templateId);
    if (idx === -1) return false;

    this._customTemplates.splice(idx, 1);
    await this._saveCustomTemplates();
    log.info(`SpamService: Deleted custom template ${templateId}`);
    return true;
  }

  /** @private */
  async _saveCustomTemplates() {
    await game.settings.set(MODULE_ID, SETTING_CUSTOM_TEMPLATES, this._customTemplates);
  }

  // ═══════════════════════════════════════════════════════════
  //  Token Resolution
  // ═══════════════════════════════════════════════════════════

  /**
   * Resolve variable tokens in a string.
   * @param {string} text Text containing {{token}} placeholders
   * @param {object} context Resolution context
   * @param {string} [context.playerName] Recipient actor name
   * @param {string} [context.networkName] Current network name
   * @returns {string} Resolved text
   */
  resolveTokens(text, context = {}) {
    if (!text) return text;

    const timeService = game.nightcity?.timeService;
    const now = timeService?.getCurrentTimestamp?.() ?? new Date().toISOString();
    const dateStr = this._formatSimpleDate(now);

    const replacements = {
      '{{playerName}}': context.playerName || 'Valued Customer',
      '{{networkName}}': context.networkName || 'CITINET',
      '{{currentDate}}': dateStr,
      '{{randomCorpo}}': this._randomPick(RANDOM_CORPOS),
      '{{randomDistrict}}': this._randomPick(RANDOM_DISTRICTS),
    };

    let result = text;
    for (const [token, value] of Object.entries(replacements)) {
      // Replace all occurrences (tokens can appear multiple times)
      result = result.split(token).join(value);
    }

    return result;
  }

  /**
   * Resolve tokens in a full template, returning a ready-to-send message object.
   * @param {object} template The spam template
   * @param {object} context Token context (playerName, networkName)
   * @returns {object} Resolved message data
   */
  resolveTemplate(template, context = {}) {
    return {
      fromName: this.resolveTokens(template.fromName, context),
      fromEmail: this.resolveTokens(template.fromEmail, context),
      subject: this.resolveTokens(template.subject, context),
      body: this.resolveTokens(template.body, context),
      category: template.category,
      templateId: template.id,
      isCustom: template.isCustom ?? false,
    };
  }

  // ═══════════════════════════════════════════════════════════
  //  Delivery
  // ═══════════════════════════════════════════════════════════

  /**
   * Send a specific spam template to one or more actors.
   * @param {string} templateId Template to send
   * @param {string[]} actorIds Recipient actor IDs
   * @returns {Promise<{success: boolean, sent: number}>}
   */
  async sendTemplate(templateId, actorIds) {
    const template = this.getTemplate(templateId);
    if (!template) {
      log.warn(`SpamService: Template not found: ${templateId}`);
      return { success: false, sent: 0 };
    }

    let sent = 0;
    for (const actorId of actorIds) {
      const actor = game.actors.get(actorId);
      if (!actor) continue;

      const context = {
        playerName: actor.name,
        networkName: game.nightcity?.networkService?.currentNetwork?.name ?? 'CITINET',
      };

      const resolved = this.resolveTemplate(template, context);
      const success = await this._deliverSpam(actorId, resolved);
      if (success) sent++;
    }

    this._sentThisSession += sent;
    log.info(`SpamService: Sent template "${template.subject}" to ${sent}/${actorIds.length} actors`);
    return { success: true, sent };
  }

  /**
   * Blast random spam to one or more actors.
   * @param {string[]} actorIds Recipient actor IDs
   * @param {number} [count=3] Number of spam messages per recipient
   * @param {string} [category='all'] Category filter
   * @returns {Promise<{success: boolean, sent: number}>}
   */
  async blast(actorIds, count = 3, category = 'all') {
    const pool = this.getTemplates(category);
    if (pool.length === 0) {
      log.warn('SpamService: No templates available for blast');
      return { success: false, sent: 0 };
    }

    let totalSent = 0;

    for (const actorId of actorIds) {
      const actor = game.actors.get(actorId);
      if (!actor) continue;

      const context = {
        playerName: actor.name,
        networkName: game.nightcity?.networkService?.currentNetwork?.name ?? 'CITINET',
      };

      // Pick random templates (allow duplicates only if pool is smaller than count)
      const picks = this._randomPickMultiple(pool, count);

      for (const template of picks) {
        const resolved = this.resolveTemplate(template, context);
        const success = await this._deliverSpam(actorId, resolved);
        if (success) totalSent++;
      }
    }

    this._sentThisSession += totalSent;
    log.info(`SpamService: Blasted ${count} spam to ${actorIds.length} actors (${totalSent} delivered)`);
    return { success: true, sent: totalSent };
  }

  /**
   * Deliver a single resolved spam message to an actor's inbox.
   * @param {string} actorId
   * @param {object} resolved Resolved message data
   * @returns {Promise<boolean>}
   * @private
   */
  async _deliverSpam(actorId, resolved) {
    try {
      const messageService = game.nightcity?.messageService;
      const messageRepo = game.nightcity?.messageRepository;
      if (!messageRepo) return false;

      const timeService = game.nightcity?.timeService;
      const timestamp = timeService?.getCurrentTimestamp?.() ?? new Date().toISOString();

      // Build message flags matching standard NCM message format
      const messageData = {
        messageId: foundry.utils.randomID(),
        from: resolved.fromEmail,
        fromActorId: null, // Spam has no real sender actor
        to: '', // Filled by repository
        toActorId: actorId,
        senderName: resolved.fromName,
        subject: resolved.subject,
        body: resolved.body.replace(/\n/g, '<br>'),
        priority: 'normal',
        timestamp,
        network: game.nightcity?.networkService?.currentNetworkId ?? 'CITINET',
        status: {
          read: false,
          saved: false,
          spam: true, // Pre-flagged as spam — goes straight to spam folder
          encrypted: false,
          infected: false,
          deleted: false,
          sent: false,
          scheduled: false,
        },
        metadata: {
          networkTrace: game.nightcity?.networkService?.currentNetworkId ?? 'CITINET',
          signalStrength: game.nightcity?.networkService?.signalStrength ?? 100,
          spamSource: 'generated',
          spamCategory: resolved.category,
          spamTemplateId: resolved.templateId,
        },
        attachments: [],
        malware: null,
      };

      // Create directly in the actor's inbox journal
      await messageRepo.createMessage(actorId, messageData);
      return true;
    } catch (err) {
      console.warn(`NCM | SpamService: Failed to deliver spam to ${actorId}`, err);
      return false;
    }
  }

  // ═══════════════════════════════════════════════════════════
  //  Auto-Spam Configuration
  // ═══════════════════════════════════════════════════════════

  /**
   * Get auto-spam config for all networks.
   * @returns {object} Map of networkId → { enabled, volume, categories }
   */
  getAutoConfig() {
    return { ...this._autoConfig };
  }

  /**
   * Get auto-spam config for a specific network.
   * @param {string} networkId
   * @returns {object|null}
   */
  getNetworkAutoConfig(networkId) {
    return this._autoConfig[networkId] ?? null;
  }

  /**
   * Set auto-spam config for a network.
   * @param {string} networkId
   * @param {object} config { enabled, volume, categories }
   * @returns {Promise<void>}
   */
  async setNetworkAutoConfig(networkId, config) {
    this._autoConfig[networkId] = {
      enabled: config.enabled ?? false,
      volume: config.volume ?? 'low',
      categories: config.categories ?? [],
    };
    await this._saveAutoConfig();
  }

  /**
   * Toggle auto-spam for a network.
   * @param {string} networkId
   * @returns {Promise<boolean>} New enabled state
   */
  async toggleNetworkAutoSpam(networkId) {
    if (!this._autoConfig[networkId]) {
      this._autoConfig[networkId] = { enabled: true, volume: 'low', categories: [] };
    } else {
      this._autoConfig[networkId].enabled = !this._autoConfig[networkId].enabled;
    }
    await this._saveAutoConfig();
    return this._autoConfig[networkId].enabled;
  }

  /**
   * Set volume for a network's auto-spam.
   * @param {string} networkId
   * @param {string} volume 'low' | 'med' | 'high' | 'flood'
   * @returns {Promise<void>}
   */
  async setNetworkVolume(networkId, volume) {
    if (!this._autoConfig[networkId]) {
      this._autoConfig[networkId] = { enabled: false, volume, categories: [] };
    } else {
      this._autoConfig[networkId].volume = volume;
    }
    await this._saveAutoConfig();
  }

  /**
   * Get number of spam messages for a given volume level.
   * @param {string} volume
   * @returns {number[]} [min, max] range
   */
  getVolumeRange(volume) {
    switch (volume) {
      case 'low': return [1, 2];
      case 'med': return [2, 4];
      case 'high': return [4, 8];
      case 'flood': return [6, 12];
      default: return [1, 2];
    }
  }

  /**
   * Check if any network has auto-spam enabled.
   * @returns {boolean}
   */
  get isAutoSpamActive() {
    return Object.values(this._autoConfig).some(c => c.enabled);
  }

  /**
   * Count networks with auto-spam enabled.
   * @returns {number}
   */
  get activeAutoSpamCount() {
    return Object.values(this._autoConfig).filter(c => c.enabled).length;
  }

  /**
   * Disable all auto-spam.
   * @returns {Promise<void>}
   */
  async disableAllAutoSpam() {
    for (const key of Object.keys(this._autoConfig)) {
      this._autoConfig[key].enabled = false;
    }
    await this._saveAutoConfig();
  }

  /** @private */
  async _saveAutoConfig() {
    await game.settings.set(MODULE_ID, SETTING_AUTO_SPAM, this._autoConfig);
  }

  // ═══════════════════════════════════════════════════════════
  //  Auto-Spam Trigger
  // ═══════════════════════════════════════════════════════════

  /**
   * Trigger auto-spam for a network connection event.
   * Called by NetworkService when a player connects to a network.
   * @param {string} networkId
   * @param {string} actorId The connecting actor
   * @returns {Promise<{sent: number}>}
   */
  async onNetworkConnect(networkId, actorId) {
    const config = this._autoConfig[networkId];
    if (!config?.enabled) return { sent: 0 };

    const [min, max] = this.getVolumeRange(config.volume);
    const count = Math.floor(Math.random() * (max - min + 1)) + min;

    // Filter templates by configured categories (or all if none specified)
    const category = config.categories?.length === 1 ? config.categories[0] : 'all';
    const result = await this.blast([actorId], count, category);

    this._autoGeneratedThisSession += result.sent;
    return { sent: result.sent };
  }

  // ═══════════════════════════════════════════════════════════
  //  Player Actor Helpers
  // ═══════════════════════════════════════════════════════════

  /**
   * Get all player-owned actors suitable for spam delivery.
   * @returns {Array<{id: string, name: string, initial: string, color: string}>}
   */
  getPlayerActors() {
    const actors = [];
    for (const actor of game.actors ?? []) {
      // Find owner user
      const ownerEntry = Object.entries(actor.ownership || {})
        .find(([uid, level]) => uid !== 'default' && level >= 3);
      const ownerUser = ownerEntry ? game.users.get(ownerEntry[0]) : null;

      // Only include player-owned actors
      if (!ownerUser || ownerUser.isGM) continue;

      actors.push({
        id: actor.id,
        name: actor.name,
        initial: (actor.name || '?').charAt(0).toUpperCase(),
        color: ownerUser.color || '#19f3f7',
      });
    }
    return actors;
  }

  // ═══════════════════════════════════════════════════════════
  //  Utilities
  // ═══════════════════════════════════════════════════════════

  /** @private */
  _randomPick(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  /** @private */
  _randomPickMultiple(arr, count) {
    if (arr.length <= count) return [...arr];

    const result = [];
    const used = new Set();
    while (result.length < count) {
      const idx = Math.floor(Math.random() * arr.length);
      if (!used.has(idx)) {
        used.add(idx);
        result.push(arr[idx]);
      }
    }
    return result;
  }

  /** @private */
  _formatSimpleDate(isoStr) {
    try {
      const d = new Date(isoStr);
      const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
      const dd = String(d.getUTCDate()).padStart(2, '0');
      const yyyy = d.getUTCFullYear();
      return `${mm}.${dd}.${yyyy}`;
    } catch {
      return '01.01.2045';
    }
  }
}
